#!/usr/bin/env bash

channel=$(cat crates/zed/RELEASE_CHANNEL)

if [ "$channel" != "stable" ]; then
  echo "this must be run on the stable release branch" >&2
  exit 1
fi

exec script/lib/bump-version.sh superzet v "" patch
